/*      This file is part of Juggluco, an Android app to receive and display         */
/*      glucose values from Freestyle Libre 2 and 3 sensors.                         */
/*                                                                                   */
/*      Copyright (C) 2021 Jaap Korthals Altes <jaapkorthalsaltes@gmail.com>         */
/*                                                                                   */
/*      Juggluco is free software: you can redistribute it and/or modify             */
/*      it under the terms of the GNU General Public License as published            */
/*      by the Free Software Foundation, either version 3 of the License, or         */
/*      (at your option) any later version.                                          */
/*                                                                                   */
/*      Juggluco is distributed in the hope that it will be useful, but              */
/*      WITHOUT ANY WARRANTY; without even the implied warranty of                   */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                         */
/*      See the GNU General Public License for more details.                         */
/*                                                                                   */
/*      You should have received a copy of the GNU General Public License            */
/*      along with Juggluco. If not, see <https://www.gnu.org/licenses/>.            */
/*                                                                                   */
/*      Fri Jan 27 12:36:58 CET 2023                                                 */


#pragma once
#include <string_view>
#include <algorithm>
#include <string.h>

constexpr const std::string_view unitlabels[]={"undetermined","mmol/L","mg/dL","both"};

struct units_t {
const char code[3];
const int type;
};
constexpr const units_t countryunits[]= {
{"AD",2},
{"AE",2},
{"AF",2},
{"AG",2},
{"AI",2},
{"AL",1},
{"AM",1},
{"AO",2},
{"AQ",0},
{"AR",2},
{"AS",2},
{"AT",2},
{"AU",1},
{"AW",2},
{"AX",1},
{"AZ",2},
{"BA",1},
{"BB",2},
{"BD",2},
{"BE",2},
{"BF",2},
{"BG",1},
{"BH",3},
{"BI",1},
{"BJ",2},
{"BL",2},
{"BM",2},
{"BN",1},
{"BO",2},
{"BQ",2},
{"BR",2},
{"BS",2},
{"BT",2},
{"BV",0},
{"BW",1},
{"BY",1},
{"BZ",2},
{"CA",1},
{"CC",1},
{"CD",2},
{"CF",2},
{"CG",2},
{"CH",1},
{"CI",2},
{"CK",1},
{"CL",2},
{"CM",2},
{"CN",1},
{"CO",2},
{"CR",2},
{"CU",2},
{"CV",2},
{"CW",2},
{"CX",1},
{"CY",2},
{"CZ",1},
{"DE",3},
{"DJ",2},
{"DK",1},
{"DM",2},
{"DO",2},
{"DZ",2},
{"EC",2},
{"EE",1},
{"EG",2},
{"EH",2},
{"ER",2},
{"ES",2},
{"ET",2},
{"FI",1},
{"FJ",1},
{"FK",1},
{"FM",2},
{"FO",1},
{"FR",2},
{"GA",2},
{"GB",1},
{"GD",2},
{"GE",2},
{"GF",2},
{"GG",1},
{"GH",2},
{"GI",1},
{"GL",1},
{"GM",2},
{"GN",2},
{"GP",2},
{"GQ",2},
{"GR",2},
{"GS",0},
{"GT",2},
{"GU",2},
{"GW",2},
{"GY",2},
{"HK",1},
{"HM",0},
{"HN",2},
{"HR",1},
{"HT",2},
{"HU",1},
{"ID",2},
{"IE",1},
{"IL",2},
{"IM",1},
{"IN",2},
{"IO",0},
{"IQ",2},
{"IR",2},
{"IS",1},
{"IT",2},
{"JE",1},
{"JM",2},
{"JO",2},
{"JP",2},
{"KE",1},
{"KG",1},
{"KH",2},
{"KI",1},
{"KM",2},
{"KN",2},
{"KP",2},
{"KR",2},
{"KW",1},
{"KY",2},
{"KZ",1},
{"LA",1},
{"LB",2},
{"LC",2},
{"LI",1},
{"LK",2},
{"LR",2},
{"LS",1},
{"LT",1},
{"LU",2},
{"LV",1},
{"LY",2},
{"MA",2},
{"MC",2},
{"MD",1},
{"ME",1},
{"MF",2},
{"MG",2},
{"MH",2},
{"MK",2},
{"ML",2},
{"MM",2},
{"MN",1},
{"MO",1},
{"MP",2},
{"MQ",2},
{"MR",2},
{"MS",2},
{"MT",1},
{"MU",1},
{"MV",2},
{"MW",1},
{"MX",2},
{"MY",1},
{"MZ",1},
{"NA",1},
{"NC",2},
{"NE",2},
{"NF",1},
{"NG",2},
{"NI",2},
{"NL",1},
{"NO",1},
{"NP",2},
{"NR",1},
{"NU",1},
{"NZ",1},
{"OM",3},
{"PA",2},
{"PE",2},
{"PF",2},
{"PG",1},
{"PH",2},
{"PK",2},
{"PL",2},
{"PM",2},
{"PN",1},
{"PR",2},
{"PS",2},
{"PT",2},
{"PW",2},
{"PY",2},
{"QA",2},
{"RE",2},
{"RO",2},
{"RS",1},
{"RU",1},
{"RW",1},
{"SA",2},
{"SB",1},
{"SC",1},
{"SD",2},
{"SE",1},
{"SG",3},
{"SH",1},
{"SI",1},
{"SJ",1},
{"SK",1},
{"SL",2},
{"SM",2},
{"SN",2},
{"SO",2},
{"SR",2},
{"SS",2},
{"ST",2},
{"SV",2},
{"SX",2},
{"SY",2},
{"SZ",1},
{"TC",2},
{"TD",2},
{"TF",0},
{"TG",2},
{"TH",2},
{"TJ",1},
{"TK",1},
{"TL",1},
{"TM",1},
{"TN",2},
{"TO",1},
{"TR",2},
{"TT",2},
{"TV",1},
{"TW",2},
{"TZ",1},
{"UA",1},
{"UG",1},
{"UM",0},
{"US",2},
{"UY",2},
{"UZ",1},
{"VA",2},
{"VC",2},
{"VE",2},
{"VG",2},
{"VI",3},
{"VN",1},
{"VU",1},
{"WF",2},
{"WS",1},
{"YE",2},
{"YT",2},
{"ZA",1},
{"ZM",1},
{"ZW",3} };



inline int getunit(const char code[2]) {
	const units_t el({{code[0],code[1]},0});
//	const units_t el(code,0);
	const units_t *ends= std::end(countryunits);
	 if(const units_t *found= std::lower_bound( std::begin(countryunits),ends , el, [](const units_t &one,const units_t &two) {return strncasecmp(one.code,two.code,2)<0;} );found!=ends&&!strncasecmp(found->code,code,2)) {
			LOGGER("getunit(%s)=%d\n",code,found->type);
		 	return found->type;
			}
		
	LOGGER("getunit(%s) not found\n",code);
	return 0;	
	}
