/* Minimal symbol list for l3_openssl_symbols_init().  Include only where symtest(name) is defined. */
symtest(EVP_DigestInit_ex);
symtest(EVP_DigestUpdate);
symtest(EVP_DigestFinal_ex);
symtest(EVP_MD_CTX_new);
symtest(EVP_MD_CTX_free);
symtest(EVP_sha1);
symtest(EVP_sha256);
symtest(EVP_sha512);
symtest(HMAC);
symtest(RAND_bytes);
symtest(EVP_CIPHER_CTX_new);
symtest(EVP_CIPHER_CTX_free);
symtest(EVP_aes_256_ctr);
symtest(EVP_EncryptInit_ex);
symtest(EVP_EncryptUpdate);
symtest(EVP_EncryptFinal_ex);
